### PR TITLE
[WIP] Initial look at a React Guide

### PR DESCRIPTION
**Pull request by orta**
So far it's pretty React Native heavy (and a WIP) so I'm gonna want web-Reacters feedback as this gets iterated on.

### CODE REVIEW

**Comment by alloy** [comment]
While we already agreed with e.g. the publishing team that we will soonish enable the ‘require function params to explicitly add types’ feature of the TS compiler, it may still be helpful to state that React component `constructor` overrides need to re-specify the props type: https://github.com/artsy/reaction/pull/394/files#r152771844

**Comment by orta** [comment]
That's a shame - yep, worth a mention

**Comment by orta** [comment]
Honestly, it sounds like something that should be in tslint

**Comment by alloy** [comment]
Maybe yeah, although they may deem it more of a DT typings issue than an actual TS one, so not sure… ¯\_(ツ)_/¯

**Comment by orta** [comment]
https://vasanthk.gitbooks.io/react-bits/

**Comment by orta** [comment]
This might be worth a 2nd re-think for artsy/README in the future. Code can probably just be C&P'd.

**Pull request closed without merging**
